import os
import random

import telebot
from telebot.types import Message


#TOKEN = '1004026853:AAH7TyM-PhWKoR8j0XZcraIyKTIif0pqFbs'
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.send_message(message.chat.id, "Hello from Wonderland! 💙")

alice_stickers = [
    'CAACAgIAAxkBAAIlEl5ATnk3_o-kRhc5rxKG6Jg04CMiAAKGAQACW90SCBDIKAipD9lUGAQ',
    'CAACAgIAAxkBAAIlFF5AToxtuxrVa2P_EsvaOpAdFVtTAAKHAQACW90SCDyuM_zA2A6EGAQ',
    'CAACAgIAAxkBAAIlFl5ATqivCMnan81dAS-se3nidrAqAAKIAQACW90SCFvCpX25FBMUGAQ',
    'CAACAgIAAxkBAAIlGF5ATrmWRmWMUqeUwggCBxIvqZOjAAKJAQACW90SCCBacVSfHiAlGAQ',
    'CAACAgIAAxkBAAIlGl5ATscH5ej_n7oTXwHT5P3bHm0GAAKKAQACW90SCAj0ldCSAnQXGAQ',
    'CAACAgIAAxkBAAIlHF5ATtae5nZQDYIgdUhBLQv-7nCkAAKLAQACW90SCFUkiX0GOxAjGAQ',
    'CAACAgIAAxkBAAIlHl5ATuO2UjKPtagDuPwaAZI_GuxqAAKMAQACW90SCFJWxbdx2-YWGAQ',
    'CAACAgIAAxkBAAIlIF5ATu9ivvNnO91pe6rK8NfAUbLtAAKNAQACW90SCC481L9ADH7WGAQ',
    'CAACAgIAAxkBAAIlIl5ATwLAkvo1qb4nBnYdbrRBLnyhAAKOAQACW90SCBOZ_nAHqJjZGAQ',
    'CAACAgIAAxkBAAIlJF5ATxGqbT_-NCaAcQZem4umMzUpAAKPAQACW90SCK2VvIE0tjXpGAQ',
    'CAACAgIAAxkBAAIlJl5ATyEPkw087q1opu4cY1eIdFLvAAKQAQACW90SCNxHHa8F6S5jGAQ',
    'CAACAgIAAxkBAAIlKF5ATzEDZwNjyKEFVWkopeIWUHa_AAKRAQACW90SCDRGaQI0kBg5GAQ',
    'CAACAgIAAxkBAAIlKl5AT0Kxl3szoj4QMYhlmX4LtXmtAAKSAQACW90SCGtMwn5wvcP8GAQ',
    'CAACAgIAAxkBAAIlLF5AT1D6hamjNgyZ9F6IWsxxqFPRAAKTAQACW90SCHxZLYzFkPAxGAQ',
    'CAACAgIAAxkBAAIlLl5AT2Hkzh_TYT5UPj4Hv1EUSvYaAAKUAQACW90SCHHTcZT2A2_aGAQ',
    'CAACAgIAAxkBAAIlMF5AT2_UMdZjhdq--haLDzZYI6EAA5UBAAJb3RIIIO17cGB5SF4YBA',
    'CAACAgIAAxkBAAIlMl5AT37SJx4Ym93TLmPbA2xIsTsDAAKWAQACW90SCIRDegskrgwjGAQ',
    'CAACAgIAAxkBAAIlNF5AT4whE0D0csIHW3jOzzaUwPqdAAKXAQACW90SCCusG2d1kyqNGAQ',
    'CAACAgIAAxkBAAIlNl5AT5sBUKbqlnmBfuapeg-bmmiSAAKYAQACW90SCNgDfbLnimOFGAQ',
    'CAACAgIAAxkBAAIlOF5AT6nHlesiVVLuRzXisq0kRqy4AAKZAQACW90SCIBg5KcPjkpZGAQ',
    'CAACAgIAAxkBAAIlOl5AT7sM2FvCy4pxKcZNB3ZoC7L3AAKbAQACW90SCLmTkbVIMHDUGAQ',
    'CAACAgIAAxkBAAIlPF5AT8q5H1AFCzq3jcizNdJBUZApAAKcAQACW90SCEJ1bQiXFbYdGAQ',
    'CAACAgIAAxkBAAIlPl5AT9coM5n9gDs-VBMvK6q1NREmAAKdAQACW90SCGDKljOL018mGAQ',
    'CAACAgIAAxkBAAIlQF5AT-TkSoTC4cFnoSNaTq5GvEa5AAKeAQACW90SCDdyny47NvZFGAQ',
    'CAACAgIAAxkBAAIlQl5AT_HspZj2JRUMd-__iKUfefcVAAKfAQACW90SCIIxccx-cO8UGAQ',
    'CAACAgIAAxkBAAIlRF5AT_97NPGOCQlMG27PKdkv9zomAAKgAQACW90SCMMSQGPEcDCVGAQ',
    'CAACAgIAAxkBAAIlRl5AUA4_1RxROdLG18jMmwV0SqiKAAKhAQACW90SCK-NOiy7s1mWGAQ',
    'CAACAgIAAxkBAAIlSF5AUBrq6m2uV4qZofMecS8FXkjzAAKiAQACW90SCAw6GzeO3rcRGAQ',
    'CAACAgIAAxkBAAIlSl5AUCmCs7pOIdz9WBi8EUMczDxnAAKjAQACW90SCCYBbJ52uU61GAQ',
]

@bot.message_handler(func = lambda message: True)
def send_sticker(message: Message):
    bot.send_sticker(message.chat.id, random.choice(alice_stickers))

# bot.send_message(393576580, 'Hi!')

@bot.message_handler(func = lambda message: True)
def upper(message: Message):
    bot.reply_to(message, message.text.upper())



bot.polling()
